export enum ErrorCode {
  CONFIG_ERROR = 'CONFIG_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  AUTH_FAILED = 'AUTH_FAILED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',

  NETWORK_ERROR = 'NETWORK_ERROR',
  TIMEOUT = 'TIMEOUT',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  API_ERROR = 'API_ERROR',
  MALFORMED_RESPONSE = 'MALFORMED_RESPONSE',
  CIRCUIT_OPEN = 'CIRCUIT_OPEN',

  UNKNOWN_ERROR = 'UNKNOWN_ERROR'
}

